version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgresql
    environment:
      POSTGRES_DB: shaman
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
